database:
  driver: '{ODBC Driver 13 for SQL Server}'
  server: 'DDAMWSQL16.sandag.org'
  database: 'demographic_warehouse'
  trusted_connection: 'yes'

staging:
  table: '[2023_12_05]'

years:
  - 2022
  - 2026
  - 2029
  - 2032
  - 2035
  - 2040
  - 2050


