version: "v1.0.3-prerelease"
seed_data: "ACS PUMS 5 year 2021"
comments: "No Comments"

sql:
  seed_households: "sql/seed_households.sql"
  seed_persons: "sql/seed_persons.sql"
  mgra_controls: "sql/mgra_controls.sql"
  region_controls: "sql/region_controls.sql"
  mgrabase: "sql/mgrabase.sql"
  load_to_database: False

economic_controls: "data/Economic Team Region Controls.csv"

synthesis_runs:
  - name: gq_mil
    configs: [configs_gq_mil, configs_common]
    data: data
    output: output_gq_mil
    num_processes: 1
  - name: gq_col
    configs: [configs_gq_col, configs_common]
    data: data
    output: output_gq_col
    num_processes: 1
  - name: gq_oth
    configs: [configs_gq_oth, configs_common]
    data: data
    output: output_gq_oth
    num_processes: 1
  - name: household
    configs: [configs_mp, configs, configs_common]
    data: data
    output: output
    num_processes: 22

years:
  - 2022
  - 2026
  - 2029
  - 2032
  - 2035
  - 2040
  - 2050