[project]
name = "population-sim"
version = "0.1.0"
description = "Population Simulation Project"
readme = "README.md"
requires-python = ">=3.8,<3.9"
dependencies = [
    "absl-py",
    "activitysim==1.1.0",
    "altair",
    "asttokens",
    "attrs",
    "backcall",
    "blinker",
    "cachetools",
    "certifi",
    "charset-normalizer",
    "click",
    "colorama",
    "cython",
    "cytoolz",
    "decorator",
    "executing",
    "gitdb",
    "gitpython",
    "idna",
    "immutabledict",
    "importlib_metadata",
    "ipython",
    "jedi",
    "jinja2",
    "jsonschema",
    "jsonschema-specifications",
    "llvmlite",
    "markdown-it-py",
    "markupsafe",
    "matplotlib",
    "matplotlib-inline",
    "mdurl",
    "msgpack",
    "narwhals",
    "numba",
    "numpy",
    "numexpr",
    "openmatrix==0.3.5.0",
    "orca==1.8",
    "ortools",
    "pandas",
    "parso",
    "pickleshare",
    "pillow",
    "pkgutil_resolve_name",
    "plotly",
    "populationsim==0.5.1",
    "prompt_toolkit",
    "protobuf",
    "psutil",
    "pure_eval",
    "pyarrow",
    "pydeck",
    "pygments",
    "pyodbc",
    "python-dateutil",
    "pytz",
    "pyyaml",
    "referencing",
    "requests",
    "rich",
    "rpds-py",
    "setuptools",
    "simwrapper",
    "smmap",
    "sqlalchemy",
    "stack-data",
    "streamlit",
    "tables",
    "toml",
    "toolz",
    "traitlets",
    "tzdata",
    "urllib3",
    "watchdog",
    "wcwidth",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["populationsim", "python", "report"]
