inherit_settings: True

multiprocess: True
num_processes: 22  # Maximum with San Diego PUMAS
cleanup_pipeline_after_run: True

slice_geography: PUMA

# Steps for base mode
# ------------------------------------------------------------------
models:
  ### mp_seed_balancing step
  - input_pre_processor
  - setup_data_structures
  - initial_seed_balancing
  - meta_control_factoring
  - final_seed_balancing
  - integerize_final_seed_weights
  ### mp_sub_balancing_mgra step
  - sub_balancing.geography=mgra
  ### mp_summarize step
  - expand_households
  - summarize
  - write_synthetic_population
  - write_data_dictionary
  - write_tables

#resume_after: integerize_final_seed_weights
resume_after:

multiprocess_steps:
  - name: mp_seed_balancing
    begin: input_pre_processor
  - name: mp_sub_balancing_mgra
    begin: sub_balancing.geography=mgra
    num_processes: 22  # Maximum with San Diego PUMAS
    slice:
      tables:
        - slice_crosswalk
        - crosswalk
      # don't slice any tables not explicitly listed above in slice.tables
      except: True
      # the following tables are added by sub_balancer and should be coalesced
      coalesce:
        - mgra_weights
        - mgra_weights_sparse
        - trace_mgra_weights
  - name: mp_summarize
    begin: expand_households
